services:
  wolbot:
    build: .
    container_name: wolbot-container  # имя контейнера
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - bot_logs:/app/logs  # том для логов, чтобы они сохранялись при перезапуске контейнера

volumes:
  bot_logs:
    driver: local
